### ISSUE TITLE
Enter transition is not working

### ISSUE THREAD

**Issue by genhoi** [robbevp/stimulus-transition#6]
@robbevp i try to use stimulus-transition for animate modal, but enter transition is not working.
Сan you tell me why the transition does not work?
[Sandbox modal sample](https://codesandbox.io/s/pensive-snowflake-ch2f9)

**Comment by robbevp** [comment]
@genhoi thanks for using this library. 
The enter transition is not displayed, because the container still has `style="display: none;"`. This is only set to block after the transition is done.

If you rework your example as following it should work:

```js
# modal_controller.js
  render() {
    if (this.openValue) {
      this.renderContainer();
      this.overlayTarget.classList.remove('hidden');
      this.panelTarget.classList.remove('hidden');
    } else {
      this.overlayTarget.classList.add('hidden');
      this.panelTarget.classList.add('hidden');
    }
  }

  renderContainer() {
    let value = this.openValue ? 'block' : 'none';
    this.element.style.setProperty('display', value);
  }

```

```html
# index.html
          <div
            data-modal-target="overlay"
            data-controller="transition"
            data-transition-initial-value
            data-transition-enter-active="ease-out duration-300"
            data-transition-enter-from="opacity-0"
            data-transition-enter-to="opacity-100"
            data-transition-leave-active="ease-in duration-200"
            data-transition-leave-from="opacity-100"
            data-transition-leave-to="opacity-0"
            data-action="transition:end-leave->modal#renderContainer"
            class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
            aria-hidden="true"
          ></div>
```

**Comment by genhoi** [comment]
Thx for help

Sorry, my fault.
> he enter transition is not displayed, because the container still has style="display: none;"



Worked solution (hidden class and style.display not work):
```js
  render() {
    if (this.openValue) {
      this.renderContainer();
    }

    this.overlayTarget.hidden = !this.openValue;
    this.panelTarget.hidden = !this.openValue;
  }
```

**Comment by chrise86** [comment]
I still can't get this working for the life of me. Does anyone have a working example to share please?

**Comment by robbevp** [comment]
> I still can't get this working for the life of me. Does anyone have a working example to share please?

What have you tried? Do you have a codepen or something similar to show what is not working?
