### ISSUE TITLE
Support Stimulus 3

### ISSUE THREAD

**Issue by tmaier** [robbevp/stimulus-transition#84]
I just checked your repo and wondered about Stimulus 3 support. 
Thanks to Dependabot, I know that there is an issue #76 

Would be great, if you would support stimulus 3...

**Comment by robbevp** [comment]
Hi @tmaier 👋 

Thanks for the reminder. I was pretty busy at work and haven't gotten around to upgrading my personal projects to stimulus 3 yet.
I've just added support for stimulus 3.0 with [`v1.1.1`](https://github.com/robbevp/stimulus-transition/releases/tag/v1.1.1)
